### ISSUE TITLE
brojKuglica.ToString() nije dobra metoda za ispis integera

### ISSUE THREAD

**Issue by lovrosverko** [Jakov764/ZavrsniRad1#1]
https://github.com/Jakov764/ZavrsniRad1/blob/4190a0a01bcb96120f27235183d91feb9fa8cda4/cvek%C5%A0praljaJakovZavrsniRad/Form1.cs#L324

int ne moraš prebacivati u string s metodom ToString(), makni je i radit će ti

**Comment by Jakov764** [comment]
return ("Broj kuglica: " + brojKuglica + ", Oblik: " + oblikSladoled + ", Cijena: " + cijena + "\r\n");
