### ISSUE TITLE
Prosljeđivanje vrijednosti

### ISSUE THREAD

**Issue by lovrosverko** [Jakov764/ZavrsniRad1#4]
https://github.com/Jakov764/ZavrsniRad1/blob/4190a0a01bcb96120f27235183d91feb9fa8cda4/cvek%C5%A0praljaJakovZavrsniRad/Sladoled.cs#L19

U konstruktoru proslijeđuješ poglešnu varijablu.

**Comment by Jakov764** [comment]
public Sladoled(int brojKuglica, string oblik, double cijena)
        {
            this.brojKuglica = brojKuglica;
            this.oblikSladoled = oblik;
            this.cijena = cijena;
        }
