### ISSUE TITLE
Tip objekta u listi

### ISSUE THREAD

**Issue by lovrosverko** [Jakov764/ZavrsniRad1#5]
https://github.com/Jakov764/ZavrsniRad1/blob/4190a0a01bcb96120f27235183d91feb9fa8cda4/cvek%C5%A0praljaJakovZavrsniRad/Form1.cs#L226

ne ide klasa Racun, nego klasa Sladoled

Želiš staviti sve sladolede u listu, tako da onda možeš izračunati total cijenu provlačenjem objekata kroz foreach petlju i zbrajanja rezultata metode Izracun().

**Comment by Jakov764** [comment]
List<Sladoled> racun = new List<Sladoled>();

**Comment by Jakov764** [comment]
Napravio
